import type { Metadata } from "next";
import "@/styles/global.css";
import { KanbanHandler } from "@/components/handles/kanban";
import { ModalHandler } from "@/components/handles/modal";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <KanbanHandler />
        <ModalHandler />
        {children}
      </body>
    </html>
  );
}
