import type { Metadata } from 'next';
import '@/styles/global.css';

import { Modal } from '@/components/molecules/modal';
import { KanbanHandler } from '@/components/handles/kanban';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="theme-dark base-1 tone palette-brand h-screen flex flex-col bg-background-base">
        <KanbanHandler />
        <Modal />
        {children}
      </body>
    </html>
  );
}
